import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Header } from "@/components/header";
import { Provider } from "jotai";
import AudioPlayerContainer from "@/components/AudioPlayerContainer";

export const metadata: Metadata = {
  title: "Prime Studios",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`dark ${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <Provider>
            <div className="min-h-screen w-full flex-1 flex-col items-center justify-center">
              <Header />
              <main className="mx-auto h-full max-w-7xl">{children}</main>
              <AudioPlayerContainer />
            </div>
          </Provider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
