import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCProvider } from "@/trpc/react";
import { Header } from "@/components/header";
import { Provider } from "jotai";
import AudioPlayerContainer from "@/components/AudioPlayerContainer";

export const metadata: Metadata = {
  title: "Prime Studios",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`dark ${geist.variable}`}>
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/byz4qug.css" />
      </head>
      <body>
        <TRPCProvider>
          <Provider>
            <div className="min-h-screen w-full flex-1 flex-col items-center justify-center">
              <Header />
              <div className="supports-[backdrop-filter]:bg-background/60 from-background/80 overflow-y-hidden bg-gradient-to-b to-[#272627]">
                <main className="mx-auto h-full max-w-7xl">{children}</main>
              </div>
              <AudioPlayerContainer />
            </div>
          </Provider>
        </TRPCProvider>
      </body>
    </html>
  );
}
